server:
  port: 8080
  name: "Prosper Eldorado"
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_CONNECTION_STRING}
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/imc-calculator?retryWrites=true&w=majority&ssl=false






